<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>ichortower.VoxBox</RootNamespace>
		<Version>0.8.0-beta</Version>
		<TargetFramework>net6.0</TargetFramework>
		<Configuration>Release</Configuration>
		<EnableHarmony>true</EnableHarmony>

		<ModFolderName>VoxBox</ModFolderName>
		<EnableModZip>false</EnableModZip>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.1.1" />
	</ItemGroup>
</Project>
